# Limpar o terminal
import os 
os.system("clear")

# Faça um algoritmo que leia dois valores inteiros A e B 
# se os valores forem iguais deverá se somar os dois
# caso contrário multiplique A por B.
#  Ao final de qualquer um dos cálculos deve-se atribuir o resultado para uma variável C e mostrar seu conteúdo na tela.

# Entrada
valor_A = int(input("Digite o valor A: "))
valor_B= int(input("Digite o valor A: "))
valor_C = int

# Processamento
if valor_A == valor_B :
    valor_A + valor_B == valor_C
else :
    valor_A * valor_B == valor_C


# Saida

print(f"valor A : {valor_A}")
print(f"valor B : {valor_B}")
print(f"valor C : {valor_C}")

 
